import type { Exercise } from "@/types";

export const EXERCISE_LIBRARY: Exercise[] = [
  {
    id: "pushups",
    name: "Pushups",
    description: "Standard pushups with chest touching the ground",
    baseReps: 15,
    baseDuration: null,
    difficultyMultiplier: 1.0,
  },
  {
    id: "squats",
    name: "Squats",
    description: "Bodyweight squats with thighs parallel to the ground",
    baseReps: 20,
    baseDuration: null,
    difficultyMultiplier: 1.0,
  },
  {
    id: "plank",
    name: "Plank",
    description: "Hold a forearm plank position with a straight body",
    baseReps: null,
    baseDuration: 60,
    difficultyMultiplier: 1.0,
  },
  {
    id: "burpees",
    name: "Burpees",
    description: "Full burpees with a jump at the top",
    baseReps: 10,
    baseDuration: null,
    difficultyMultiplier: 1.0,
  },
  {
    id: "lunges",
    name: "Lunges",
    description: "Alternating forward lunges, count each leg",
    baseReps: 16,
    baseDuration: null,
    difficultyMultiplier: 1.0,
  },
  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    description: "Alternating mountain climbers at a steady pace",
    baseReps: null,
    baseDuration: 45,
    difficultyMultiplier: 1.0,
  },
  {
    id: "jumping-jacks",
    name: "Jumping Jacks",
    description: "Full jumping jacks with arms overhead",
    baseReps: 30,
    baseDuration: null,
    difficultyMultiplier: 1.0,
  },
  {
    id: "sit-ups",
    name: "Sit-ups",
    description: "Full sit-ups with feet on the ground",
    baseReps: 20,
    baseDuration: null,
    difficultyMultiplier: 1.0,
  },
  {
    id: "high-knees",
    name: "High Knees",
    description: "Running in place bringing knees to waist height",
    baseReps: null,
    baseDuration: 40,
    difficultyMultiplier: 1.0,
  },
  {
    id: "wall-sit",
    name: "Wall Sit",
    description: "Hold a seated position against a wall with thighs parallel",
    baseReps: null,
    baseDuration: 45,
    difficultyMultiplier: 1.0,
  },
];
